### PR TITLE
Add vendor directory to repository for packaging

### PR DESCRIPTION
**Pull request by mjura**

### CODE REVIEW

**Comment by MalloZup** [comment]
We need vendor for obs right?

**Comment by mjura** [comment]
@MalloZup: yes, we need this to build OBS package. OBS can't get these packages during build.

**Comment by MalloZup** [comment]
Yop i agree with @inercia here. I did not want to say but it was what i wad thinking :+1: :) if we can spare vendor would awesome

**Comment by cyphar** [comment]
I would concur with using Go 1.11 modules but it should be noted that building in OBS with them is still a bit difficult. What we do in umoci is to use Go 1.11 modules and then do `go mod vendor` to fill the vendor directory -- which allows old Go compilers to build. I'm not a huge fan of doing it all in Concourse, but feel free to do it however you like. :D

Also note that if you build in OBS you'll need to disable Go modules (`GO111MODULES=off`) because otherwise newer Go compilers will try to download from the internet which isn't fun.

(The long-term plan will be to have an OBS service for doing this -- which would auto-fetch all of the dependencies during OBS builds -- or having Fedora-style automated packaging but I'm more in favor of the former.)

**Comment by cyphar** [comment]
Also, holy shit! 1M lines of dependencies.

**Comment by mjura** [comment]
ok, vendors will be pre-fetched and provided in tarball

**Pull request closed without merging**
