### PR TITLE
Add packaging kubic-init script for concourse job

### PR DESCRIPTION
**Pull request by mjura**

### CODE REVIEW

**Comment by mjura** [comment]
It was tested

**Comment by mjura** [comment]
@MalloZup thank you for suggestions, unfortunately we would like to enable auto-build for this package in OBS https://build.opensuse.org/package/show/devel:kubic/kubic-init to do this we have to use our concourse system to build it and then we have to adopt and generate `kubic-init.spec` file according to OBS and concourse requirements

**Comment by mjura** [comment]
Here is automation part which will use it https://gitlab.suse.de/docker/automation/merge_requests/247

**Comment by MalloZup** [comment]
let's merge it.

@mjura @MaximilianMeister thank you for this :santa:

**Pull request merged**
