### PR TITLE
Favor simplicity over to much statements

### PR DESCRIPTION
**Pull request by MalloZup**
In this PR i remove 3 statements.

1) The goal statement is to much generic ( for me is better remove it)
2) The statement about security, is imho something better to don't mention it because it will give more a bad impression
3) I remove the `in theory` it should work for other OS. ( in opensource either you state what you support or you don't say in `theory` ambiguous statement). This in `theory` as user would give me a bad feeling

I had the feeling that trying to say to much over our intents would be more harmful for us then leave some statements opens.  I followed also what i see in upstream projects

### CODE REVIEW

**Comment by dannysauer** [comment]
The first sentence removal is good.  Regarding the "in theory" part - is the goal still to eventually support other OS / environments?  If so, it might be beneficial to retain some statement to that effect (probably reworded; I also don't like "in theory") to encourage interested third-parties who might want to make such a contribution.

**Comment by MalloZup** [comment]
Yop i get the point, how would you state this without in theory?

**Comment by dannysauer** [comment]
Hrmm.  Maybe something along the lines of "The only known obstacle to kubic-init being used outside of Kubic is developer time; pull requests are welcome"?

**Comment by MalloZup** [comment]
@dannysauer i am merging this, feel free to make PR for writing the better line.

**Pull request merged**
