### PR TITLE
downgrade version

### PR DESCRIPTION
**Pull request by MalloZup**
Update version to `0.0.3`

### CODE REVIEW

**Comment by nirmoy** [comment]
looks like downgrade to me :)

**Comment by MalloZup** [comment]
> Lets change the change log to something like "kubic-init: fix version"
> 
> I think we should have a proper format for for commit message so that generating changelog gets easier. I would prefer ": ".

yop correct. where do you prefer the `:`? in commit msg?.

Imho the Changelog.MD should be done by humans, i think once we merge a PR we should check if it is important or not.

I would not add commit msg as  changelog entry because  mostly the commit are in deep technical explanation and a changelog entry can be a summary of that. ( this is a nice page https://keepachangelog.com/en/1.0.0/#bad-practices)

**Comment by MalloZup** [comment]
yop i can change the changelog also for that.

Imho at moment we are doing the changelog here:  
https://github.com/kubic-project/kubic-init/releases/tag/untagged-aa85662dec6234e18500

This text will then copied to `changelog.md` once we decide to put the `0.0.4` version out.

Imho we can do also PR to changelog.md directly i am not against, is both ok for me :smile:

**Comment by nirmoy** [comment]
@MalloZup I am not saying copy commit mesg to change log. when there is a commit lets say "fix memleak" we never know in which component  -> "kubic-init: fix memleak" can give use hint so that we can write better changelog

**Comment by MalloZup** [comment]
right ! good tip.
We could maybe add this info to devel guide somewhere, in a section commit messages

**Comment by MalloZup** [comment]
https://github.com/kubic-project/kubic-init/issues/163

**Comment by MalloZup** [comment]
i have used this `release: downgrade VERSION file` we might etablish kind of valid prefix we could use as convention.

**Comment by MalloZup** [comment]
we can merge this, however feel free to update the issue linked so we can have kind of guidelines for that in future

**Pull request merged**
