### PR TITLE
Get rid of our own Init/Join code

### PR DESCRIPTION
**Pull request by inercia**
Replace the Init/Join code by the `kubeadm.NewInit()/NewJoin()` functions.
Unsorted fixes.

### CODE REVIEW

**Comment by sysrich** [comment]
is moving to opensuse leap sensible? it is likely to have the same behaviour as Tumbleweed as soon as it includes the new systemd, which could be as soon as 15.1 (currently in development)

**Comment by ereslibre** [comment]
> is moving to opensuse leap sensible? it is likely to have the same behaviour as Tumbleweed as soon as it includes the new systemd, which could be as soon as 15.1 (currently in development)

If this is the case, this will bite us in the (near) future. I don't think we should workaround this right now, but instead debug why `systemctl` is not working as expected.

**Comment by inercia** [comment]
>> is moving to opensuse leap sensible? it is likely to have the same behaviour as Tumbleweed as soon as it includes the new systemd, which could be as soon as 15.1 (currently in development)
> If this is the case, this will bite us in the (near) future. I don't think we should workaround this right now, but instead debug why systemctl is not working as expected.

Right now we don't care so much about the base image used for running `kubic-init` as about having a functional `kubic-init` that can create a functional cluster. As many other `TODO`s in this repo, we will have to fix them at some moment, but I think we should stick to our current priorities...

**Comment by inercia** [comment]
I think we can merge this PR as the main concerns expressed are related to a minor issue (the base for the docker image)...

**Pull request merged**
